<p>
    UNLwebaudit helps you maintain your site by running automatic audits to find potential problems with HTML markup, accessibility, UNL web standards and broken links.  It also provides a <a href="<?php echo $base_url . 'registry/' ?>">registry</a> of sites at UNL, which can be used as a WHOIS service or as a source of role assignments that can be used by other systems like <a href="http://ucommchat.unl.edu/">UNLchat</a>.  
</p>
<h2>Why Audit?</h2>
<div class="wdn-grid-set">
    <div class="bp1-wdn-col-two-thirds">
        <dl>
            <dt>
                TO ENSURE CONSISTENT EXPERIENCE.
            </dt>
            <dd>
                UNL’s web quality assurance effort provides developers with information needed to maintain a consistent, high-quality user experience for site visitors.
            </dd>
            <dt>
                TO ENSURE DEVICE COMPATIBILITY.
            </dt>
            <dd>
                By maintaining high compliance to international standards for code validity, UNLedu is usable on all modern, standards-compliant browsers. By moving sites to responsive frameworks, we gain full fidelity on mobile devices.
            </dd>
            <dt>
                TO DO THE RIGHT THING.
            </dt>
            <dd>
                The UNLedu Web Framework, as delivered to developers, is in compliance with current web accessibility standards and laws, and incorporates some technologies that provide additional benefit to persons using assistive technologies. The framework also incorporates integrations with UNL’s single sign-on service for authentication.
            </dd>
            <dt>
                TO MAKE IT AWESOME.
            </dt>
            <dd>
                The UNLedu Web Framework is much more than a template, or a set of design instructions. Today it's an aggregation of best ideas for design and computing from across the university, incorporating authentication, emergency notification, constituent chat and other features. As it continues to evolve, along with the web, its relevance and its ability to serve our users is limited only by our collective imaginations.
            </dd>
        </dl>
    </div>
    <div class="bp1-wdn-col-one-third">
        <figure class="wdn-frame">
            <img src="<?php echo $base_url ?>plugins/theme_unl/www/themes/unl/html/images/example-scan.png" alt="An example report that was generated by webaudit." />
            <figcaption>
                An example report that was generated by UNLwebaudit
            </figcaption>
        </figure>
    </div>
</div>
